apiVersion: v1
kind: Service
metadata:
  name: atualiza-service
  labels:
    app: atualiza-service
spec:
  selector:
    app: atualiza-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
