apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'cadastro-service'
        static_configs:
          - targets: ['cadastro-service:80']

      - job_name: 'atualiza-service'
        static_configs:
          - targets: ['atualiza-service:80']

      - job_name: 'consulta-service'
        static_configs:
          - targets: ['consulta-service:80']

      - job_name: 'exclui-service'
        static_configs:
          - targets: ['exclui-service:80']

      - job_name: 'persistencia-service'
        static_configs:
          - targets: ['persistencia-service:1234']
