apiVersion: v1
kind: Service
metadata:
  name: exclui-service
  labels:
    app: exclui-service
spec:
  selector:
    app: exclui-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
