apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistencia-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: persistencia
  template:
    metadata:
      labels:
        app: persistencia
    spec:
      containers:
      - name: persistencia-container
        image: persistenciaservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 1234
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume
        configMap:
          name: persistencia-config
